apiVersion: v1
kind: Service
metadata:
  name: kubernetesdemo2
  namespace: dev
  labels:
    app: kubernetesdemo2
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: kubernetesdemo2
