apiVersion: v1
data:
  gitlab.root.email: UmFkb3NsYXcuT3NpbnNraUBjd3NmZS5wbA==
  gitlab.root.password: dDNycm9yeXphY2ph
  gitlab.smtp.password: cGFzc3dvcmQ=
  gitlab.imap.password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: gitlab-secrets
  namespace: ci
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: ci
  labels:
    app: gitlab
spec:
  replicas: 1
  serviceName: gitlab
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
        env: ci
    spec:
      imagePullSecrets:
      - name: registrypullsecret
      containers:
      - name: gitlab
        image: sameersbn/gitlab:10.7.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 22
        env:
        - name: DEBUG
          value: "true"
        - name: "TZ"
          value: "Europe/Warsaw"
        - name: GITLAB_TIMEZONE
          value: "Warsaw"
        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: "long-and-random-alpha-numeric-string"
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: "long-and-random-alphanumeric-string"
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: "long-and-random-alpha-numeric-string"
        - name: GITLAB_HOST
          value: "gitlab.example.pl"
        - name: GITLAB_PORT
          value: "10443"
        - name: GITLAB_SSH_PORT
          value: "10022"
        - name: GITLAB_RELATIVE_URL_ROOT
          value: ""
        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"
        - name: GITLAB_ROOT_EMAIL
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab.root.email
        - name: GITLAB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab.root.password
        - name: GITLAB_EMAIL
          value: "notifications@example.com"
        - name: GITLAB_EMAIL_REPLY_TO
          value: "noreply@example.com"
        - name: GITLAB_INCOMING_EMAIL_ADDRESS
          value: "reply@example.com"
        - name: GITLAB_BACKUP_SCHEDULE
          value: "daily"
        - name: GITLAB_BACKUP_TIME
          value: "01:48"
        - name: GITLAB_REGISTRY_ENABLED
          value: "true"
        - name: GITLAB_PAGES_ENABLED
          value: "true"
        - name: SMTP_ENABLED
          value: "false"
        - name: SMTP_DOMAIN
          value: "example.com"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          value: "mailer@example.com"
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab.smtp.password
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_AUTHENTICATION
          value: "login"
        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: "imap.gmail.com"
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_USER
          value: "mailer@example.com"
        - name: IMAP_PASS
          valueFrom:
             secretKeyRef:
               name: gitlab-secrets
               key: gitlab.imap.password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "false"
        - name: DB_HOST
          value: "gitlab-postgresql.ci"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gitlab-postgresql-secrets
              key: gitlab.postgresql.username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: gitlab-postgresql-secrets
              key: gitlab.postgresql.password
        - name: DB_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "gitlab-redis.ci"
        - name: REDIS_PORT
          value: "6379"
        - name: UNICORN_WORKERS
          value: "3"
        - name: UNICORN_TIMEOUT
          value: "120"
        - name: OAUTH_ENABLED
          value: "false"
        - name: SSL_SELF_SIGNED
          value: "true"
        - name: GITLAB_HTTPS
          value: "true"
        - name: SSL_KEY_PATH
          value: "/home/git/data/certs/gitlab.key"
        - name: SSL_CERTIFICATE_PATH
          value: "/home/git/data/certs/gitlab.crt"
        - name: SSL_DHPARAM_PATH
          value: "/home/git/data/certs/dhparam.crt"
        - name: SSL_CA_CERTIFICATES_PATH
          value: "/home/git/data/certs/cacrt/ca.crt"
        volumeMounts:
          - mountPath: "/home/git/data"
            name: gitlab-persistent-data-volume
          - mountPath: "/home/git/data/certs/"
            name: gitlab-crt-conf
            readOnly: true
          - mountPath: "/home/git/data/certs/cacrt/"
            name: gitlab-ca-crt-conf
            readOnly: true
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2.1
            memory: 5Gi
      volumes:
        - configMap:
            name: gitlab-crt-config
          name: gitlab-crt-conf
        - configMap:
            name: gitlab-ca-crt-config
          name: gitlab-ca-crt-conf
  volumeClaimTemplates:
    - metadata:
        name: gitlab-persistent-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: ci
  labels:
    app: gitlab
spec:
  ports:
  - port: 10443
    name: httpsport
    protocol: TCP
    targetPort: 443
  - port: 10022
    name: sshport
    protocol: TCP
    targetPort: 22
  type: LoadBalancer
  selector:
    app: gitlab
